=== Crown-Commercial-Service/digitalmarketplace-api/schemata/g6-scs-schema.json
{
   "id" : "G6 Submissions SCS Schema",
   "$schema" : "http://json-schema.org/schema#",
   "type" : "object",
   "properties" :
      {
         "id" :
            {
               "type" : "integer"
            },
         "supplierId" :
            {
               "type" : "string",
               "pattern" : "\\d+"
            },
         "lot" :
            {
               "type" : "string",
               "pattern" : "SCS"
            },
         "title" :
            {
               "type" : "string"
            },
         "serviceSubmitted" :
            {
               "type" : "boolean"
            },
         "lastUpdated" :
            {
               "type" : "string"
            },
         "lastUpdatedEmail" :
            {
               "type" : "string"
            },
         "lastCompleted" :
             {
                "type" : "string"
             },
         "lastCompletedByEmail" :
            {
               "type" : "string"
            },
         "pageSequence" :
            {
               "type" : "array",
               "items" :
                  {
                     "type" : "number",
                     "uniqueItems" : true
                  }
            },
         "completedPages" :
            {
               "type" : "array",
               "minItems": 8,
               "maxItems": 8,
               "uniqueItems": true,
               "items" :
                  {
                     "type" : "object",
                     "properties" :
                        {
                           "id" :
                              {
                                 "type" : "integer"
                              },
                           "pageNumber" :
                              {
                                 "type" : "integer"
                              },
                           "listingId" :
                              {
                                 "type" : "integer"
                              },
                           "responses" :
                              {
                                 "type" : "object"
                              },
                           "submittedDocuments" :
                              {
                                 "type" : "object"
                              }
                        },
                        "required": ["id", "pageNumber", "listingId", "responses", "submittedDocuments"]
                  }
            }
      },
      "required": ["id", "supplierId", "lot", "title", "serviceSubmitted", "lastUpdated", "lastUpdatedEmail", "lastCompleted",
                   "lastCompletedByEmail", "pageSequence", "completedPages"]
}

=== Crown-Commercial-Service/digitalmarketplace-api/example_listings/scs-listing.json
{
   "id" : 1,
   "supplierId" : "1",
   "lot" : "SCS",
   "title" : "My service name",
   "serviceSubmitted" : true,
   "lastUpdated" : "Dec 8, 2014 12:50:08 PM",
   "lastUpdatedEmail" : "test_g6_supplier@digital.cabinet-office.gov.uk",
   "lastCompletedByEmail" : "test_g6_supplier@digital.cabinet-office.gov.uk",
   "lastCompleted" : "Dec 8, 2014 12:50:14 PM",
   "pageSequence" :
      [
         3,
         4,
         5,
         6,
         7,
         8,
         10,
         20
      ],
   "completedPages" :
      [
         {
            "id" : 12345,
            "pageNumber" : 3,
            "listingId" : 1,
            "responses" :
               {
                  "p3q1" : "[\"Ongoing support\",\"Planning\",\"Training\"]"
               },
            "submittedDocuments" :
               {
               }
         },
         {
            "id" : 12346,
            "pageNumber" : 4,
            "listingId" : 1,
            "responses" :
               {
                  "p4q1" : "My service name",
                  "p4q2" : "My service summary"
               },
            "submittedDocuments" :
               {
               }
         },
         {
            "id" : 12347,
            "pageNumber" : 5,
            "listingId" : 1,
            "responses" :
               {
                  "p5q2" : "[\"Benefit 1\",\"Benefit 2\"]",
                  "p5q1" : "[\"Feature 1\",\"Feature 2\"]"
               },
            "submittedDocuments" :
               {
               }
         },
         {
            "id" : 12345,
            "pageNumber" : 6,
            "listingId" : 1,
            "responses" :
               {
                  "p6q1" : "test_document.pdf"
               },
            "submittedDocuments" :
               {
                  "p6q1" :
                     {
                        "id" : 2,
                        "filename" : "test_document.pdf",
                        "type" : "pdf",
                        "listingId" : 1,
                        "questionId" : "p6q1",
                        "documentUrl" : "https://document-storage.gov.uk/gds-g6-submissions/supplier/listing/1-service-definition-document.pdf"
                     }
               }
         },
         {
            "id" : 12348,
            "pageNumber" : 7,
            "listingId" : 1,
            "responses" :
               {
                  "p7q3" : "test_document.pdf",
                  "p7q2" : "Month",
                  "p7q1" : "Yes"
               },
            "submittedDocuments" :
               {
                  "p7q3" :
                     {
                        "id" : 3,
                        "filename" : "test_document.pdf",
                        "type" : "pdf",
                        "listingId" : 1,
                        "questionId" : "p7q3",
                        "documentUrl" : "https://document-storage.gov.uk/gds-g6-submissions/supplier/listing/1-terms-and-condtions.pdf"
                     }
               }
         },
         {
            "id" : 12349,
            "pageNumber" : 8,
            "listingId" : 1,
            "responses" :
               {
                  "p8q1Interval" : "Minute",
                  "p8q3" : "No",
                  "p8q1Unit" : "Licence",
                  "p8q2" : "Yes",
                  "p8q1" : "£10 to £100 per licence per minute",
                  "p8q7" : "test_document.pdf",
                  "p8q1MaxPrice" : "100",
                  "p8q6" : "test_document.pdf",
                  "p8q1MinPrice" : "10"
               },
            "submittedDocuments" :
               {
                  "p8q7" :
                     {
                        "id" : 4,
                        "filename" : "test_document.pdf",
                        "type" : "pdf",
                        "listingId" : 1,
                        "questionId" : "p8q7",
                        "documentUrl" : "https://document-storage.gov.uk/gds-g6-submissions/supplier/listing/1-sfia-rate-card.pdf"
                     },
                  "p8q6" :
                     {
                        "id" : 5,
                        "filename" : "test_document.pdf",
                        "type" : "pdf",
                        "listingId" : 1,
                        "questionId" : "p8q6",
                        "documentUrl" : "https://document-storage.gov.uk/gds-g6-submissions/supplier/listing/1-pricing-document.pdf"
                     }
               }
         },
         {
            "id" : 12350,
            "pageNumber" : 10,
            "listingId" : 1,
            "responses" :
               {
                  "p10q2" : "No",
                  "p10q3" : "My availability",
                  "p10q4" : "My response time",
                  "p10q5" : "No",
                  "p10q1" : "[\"Email\",\"Phone\",\"Live chat\"]"
               },
            "submittedDocuments" :
               {
               }
         },
         {
            "id" : 12351,
            "pageNumber" : 20,
            "listingId" : 1,
            "responses" :
               {
                  "p20q1" : "[\"I have a certificate\",\"And another certificate\"]"
               },
            "submittedDocuments" :
               {
               }
         }
      ]
}
