=== Crown-Commercial-Service/digitalmarketplace-api/json_schemas/g5-services-schema.json
{
  "id": "G5 Services Schema",
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^5\\..*"
    },
    "state": {
      "type": "string",
      "pattern": "^(disabled|enabled|published)$"
    },
    "supplierId": {
      "type": "integer"
    },
    "lot": {
      "type": "string",
      "pattern": "^(SaaS|PaaS|IaaS|SCS|missing)$"
    },
    "title": {
      "type": "string"
    },
    "serviceName": {
      "type": "string"
    },
    "serviceSummary": {
      "type": "string"
    },
    "serviceBenefits": {
      "type": "array",
      "maxItems": 10,
      "items": {
        "type": "string"
      }
    },
    "serviceFeatures": {
      "type": "array",
      "maxItems": 10,
      "items": {
        "type": "string"
      }
    },
    "serviceDefinitionDocumentURL": {
      "type": "string",
      "format": "uri"
    },
    "termsAndConditionsDocumentURL": {
      "type": "string"
    },
    "pricingDocumentURL": {
      "type": "string",
      "format": "uri"
    },
    "sfiaRateDocumentURL": {
      "type": "string",
      "format": "uri"
    },
    "additionalDocumentURLs": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "minimumContractPeriod": {
      "type": "string",
      "pattern": "^(hour|day|month|year|other)$"
    },
    "freeOption": {
      "type": "boolean"
    },
    "trialOption": {
      "type": "boolean"
    },
    "terminationCost": {
      "type": "boolean"
    },
    "priceMin": {
      "type": "number"
    },
    "priceUnit": {
      "type": "string"
    },
    "priceString": {
      "type": "string"
    },
    "serviceTypes": {
      "oneOf": [
        {
          "id": "SaaS - G5",
          "type": "array",
          "uniqueItems": true,
          "maxItems": 25,
          "items": {
            "type": "string",
            "pattern": "^(Accessibility|Agile Tools|Analytics|Antispam / CAPTCHA|Asset Management|Content Management Systems \\(CMS\\)|Customer Relationship Management \\(CRM\\)|Data Visualisation|EDRM / Collaboration|Email|End User Device \\(EUD\\)|Enterprise Resource Planning|Forms|Gamification|Geographic Search|Identity|Learning Management Systems \\(LMS\\)|Office Productivity|Polls/Surveys|Search|Service Monitoring|Simulation & Training|Un-listed|User Alerts)$"
          }
        },
        {
          "id": "SaaS - Updated to G6",
          "type": "array",
          "uniqueItems": true,
          "maxItems": 25,
          "items": {
            "type": "string",
            "pattern": "^(Accounting and finance|Business intelligence and analytics|Collaboration|Customer relationship management \\(CRM\\)|Creative and design|Data management|Electronic document and records management \\(EDRM\\)|Energy and environment|Healthcare|Human resources and employee management|IT management|Legal|Libraries|Marketing|Operations management|Project management and planning|Sales|Schools and education|Security|Software development tools|Telecoms|Transport and logistics)$"
          }
        },
        {
          "id": "PaaS - G5",
          "type": "array",
          "uniqueItems": true,
          "maxItems": 25,
          "items": {
            "type": "string",
            "pattern": "^(Application Deployment|Components)$"
          }
        },
        {
          "id": "IaaS - G5",
          "type": "array",
          "uniqueItems": true,
          "maxItems": 25,
          "items": {
            "type": "string",
            "pattern": "^(Compute|Content Delivery Network \\(CDN\\)|Storage|Other)$"
          }
        },
        {
          "id": "SCS - G5",
          "type": "array",
          "uniqueItems": true,
          "maxItems": 25,
          "items": {
            "type": "string",
            "pattern": "^(Business Analysis|Data quality|Data recovery, conversion and migration|Data storage consultancy|Deployment|Design and Development|Design Authority|eDiscovery|Digital archiving|Enterprise Architecture|Helpdesk|Information Management and Digital Continuity|Onboarding services|Project Management, Programme Management and Governance|Project Specification and Selection|Service Integration and Management Services \\(SIAM\\)|Service Management|Software Support|Specialist Cloud Services|Transition Management|User Management)$"
          }
        },
        {
          "id": "SCS - Updated to G6",
          "type": "array",
          "uniqueItems": true,
          "maxItems": 25,
          "items": {
            "type": "string",
            "pattern": "^(Implementation|Ongoing Support|Planning|Testing|Training)$"
          }
        }
      ]
    },
    "educationPricing": {
      "type": "boolean"
    },
    "networksConnected": {
      "type": "array",
      "uniqueItems": true,
      "maxItems": 7,
      "items": {
        "type": "string",
        "pattern": "^(Internet|Public Services Network \\(PSN\\)|Government Secure intranet \\(GSi\\)|Police National Network \\(PNN\\)|New NHS Network \\(N3\\)|Joint Academic Network \\(JANET\\)|Other)$"
      }
    },
    "apiAccess": {
      "type": "boolean"
    },
    "elasticCloud": {
      "type": "boolean"
    },
    "guaranteedResources": {
      "type": "boolean"
    },
    "persistentStorage": {
      "type": "boolean"
    },
    "openStandardsSupported": {
      "type": "boolean"
    },
    "openSource": {
      "type": "boolean"
    },
    "serviceOnBoarding": {
      "type": "boolean"
    },
    "serviceOffBoarding": {
      "type": "boolean"
    },
    "dataExtractionRemoval": {
      "type": "boolean"
    },
    "datacentresEUCode": {
      "type": "boolean"
    },
    "dataBackupRecovery": {
      "type": "boolean"
    },
    "selfServiceProvisioning": {
      "type": "boolean"
    },
    "supportForThirdParties": {
      "type": "boolean"
    }
  },
  "required": [
    "id",
    "state",
    "supplierId",
    "lot",
    "title",
    "serviceName",
    "serviceSummary",
    "serviceDefinitionDocumentURL",
    "termsAndConditionsDocumentURL",
    "pricingDocumentURL",
    "minimumContractPeriod",
    "freeOption",
    "trialOption",
    "terminationCost",
    "priceMin",
    "priceUnit",
    "priceString"
  ]
}

=== Crown-Commercial-Service/digitalmarketplace-api/example_listings/G5.json
{
  "id":"5.G2.0123.456",
  "serviceName":"Some G5 Data Collection",
  "title":"Some G5 Data Collection",
  "serviceSummary":"A simple and easy solution for G5 data stuff.",
  "priceMin":20.0,
  "priceUnit":"Per User / Month",
  "priceString":"20.0 Per User / Month",
  "supplierId":1,
  "state":"published",
  "lot":"SaaS",
  "serviceTypes":[
    "Marketing",
    "Software development tools"
  ],
  "minimumContractPeriod":"year",
  "freeOption":false,
  "trialOption":false,
  "terminationCost":false,
  "networksConnected":[
    "Internet"
  ],
  "apiAccess":false,
  "openStandardsSupported":false,
  "openSource":false,
  "serviceOnBoarding":true,
  "serviceOffBoarding":true,
  "dataExtractionRemoval":true,
  "datacentresEUCode":true,
  "dataBackupRecovery":true,
  "selfServiceProvisioning":false,
  "supportForThirdParties":true,
  "educationPricing":false,
  "pricingDocumentURL":"http://assets-production.govstore.service.gov.uk/G5/Supplier/someId/Pricing Document.docx",
  "serviceDefinitionDocumentURL":"http://assets-production.govstore.service.gov.uk/G5/Supplier/someId/Service Definition.docx",
  "sfiaRateDocumentURL":"http://assets-production.govstore.service.gov.uk/G5/Supplier/someId/Rate card.docx",
  "termsAndConditionsDocumentURL":"http://assets-production.govstore.service.gov.uk/G5/Supplier/someId/TandC_data_collection.doc",
  "additionalDocumentURLs": [
    "http://assets-production.govstore.service.gov.uk/G5/Supplier/someId/Appendix 1.pdf",
    "http://assets-production.govstore.service.gov.uk/G5/Supplier/someId/Appendix 2.pdf"
  ]
}
