=== Crown-Commercial-Service/digitalmarketplace-api/json_schemas/new-supplier.json
{
  "$schema": "http://json-schema.org/schema#",
  "additionalProperties": false,
  "properties": {
    "clients": {
      "items": {
        "type": "string"
      },
      "maxItems": 10,
      "minItems": 0,
      "type": "array"
    },
    "companiesHouseNumber": {
      "maxLength": 8,
      "minLength": 8,
      "type": "string"
    },
    "contactInformation": {
      "items": {
        "$ref": "file:json_schemas/contact-information.json"
      },
      "minItems": 1,
      "type": "array"
    },
    "description": {
      "type": "string"
    },
    "dunsNumber": {
      "pattern": "^[0-9]+$",
      "type": "string"
    },
    "eSourcingId": {
      "pattern": "^[0-9]+$",
      "type": "string"
    },
    "name": {
      "type": "string"
    }
  },
  "required": [
    "contactInformation",
    "dunsNumber",
    "name"
  ],
  "title": "Schema to validate new supplier sign-up",
  "type": "object"
}

=== Crown-Commercial-Service/digitalmarketplace-api/example_listings/supplier_creation.json
{
  "name": "Example Company Limited",
  "description": "Example Company Limited is an innovation station sensation; we deliver software so bleeding edge you literally won't be able to run any of it on your systems.",
  "contactInformation": [
    {
      "contactName": "John Example",
      "email": "j@examplecompany.biz",
      "phoneNumber": "07309404738",
      "address1": "123 Fake Street",
      "city": "London",
      "postcode": "F4 K1E"
    },
    {
      "id": 1,
      "contactName": "Don",
      "email": "don@don.com",
      "phoneNumber": "020 7918 9200",
      "address1": "4 Don Hill",
      "city": "London",
      "postcode": "EC1A D0N"
    }
  ],
  "dunsNumber": "333333333",
  "companiesHouseNumber": "SC000111"
}
