=== Crown-Commercial-Service/digitalmarketplace-api/json_schemas/services-g6-scs.json
{
   "id": "G6 Submissions SCS Schema",
   "$schema": "http://json-schema.org/schema#",
   "type": "object",
   "additionalProperties": false,
   "properties": {
    "id": {
      "type": "string",
      "pattern": "^([0-9]{16})$"
    },
      "supplierId": {
         "type": "integer"
      },
      "lot": {
         "type": "string",
         "pattern": "^SCS$"
      },
      "title": {
         "type": "string"
      },
      "lastUpdated": {
         "type": "string",
         "format": "date-time"
      },
      "lastUpdatedByEmail": {
         "type": "string"
      },
      "lastCompleted": {
         "type": "string",
         "format": "date-time"
      },
      "lastCompletedByEmail": {
         "type": "string"
      },
      "serviceTypes": {
         "type": "array",
         "uniqueItems": true,
         "maxItems": 5,
         "items": {
            "type": "string",
            "pattern": "^(Implementation|Ongoing support|Planning|Testing|Training)$"
         }
      },
      "serviceName": {
         "type": "string"
      },
      "serviceSummary": {
         "type": "string"
      },
      "serviceBenefits": {
         "type": "array",
         "maxItems": 10,
         "items": {
            "type": "string"
         }
      },
      "serviceFeatures": {
         "type": "array",
         "maxItems": 10,
         "items": {
            "type": "string"
         }
      },
      "serviceDefinitionDocument": {
         "type": "string"
      },
      "serviceDefinitionDocumentURL": {
         "type": "string",
         "format": "uri"
      },
      "termsAndConditionsDocument": {
         "type": "string"
      },
      "termsAndConditionsDocumentURL": {
         "type": "string"
      },
      "minimumContractPeriod": {
         "type": "string",
         "pattern": "^(Hour|Day|Month|Year|Other)$"
      },
      "terminationCost": {
         "type": "boolean"
      },
      "priceMin": {
         "type": "number"
      },
      "priceMax": {
         "type": ["number", "null"]
      },
      "priceUnit": {
         "type": "string",
         "pattern": "^(Unit|Person|Licence|User|Device|Instance|Server|Virtual machine|Transaction|Megabyte|Gigabyte|Terabyte)$"
      },
      "priceInterval": {
         "type": "string",
        "pattern": "^(||Second|Minute|Hour|Day|Week|Month|Quarter|6 months|Year)$"
      },
      "priceString": {
         "type": "string"
      },
      "vatIncluded": {
         "type": "boolean"
      },
      "educationPricing": {
         "type": "boolean"
      },
      "pricingDocument": {
         "type": "string"
      },
      "pricingDocumentURL": {
         "type": "string",
         "format": "uri"
      },
      "sfiaRateDocument": {
         "type": "string"
      },
      "sfiaRateDocumentURL": {
         "type": "string",
         "format": "uri"
      },
      "supportForThirdParties": {
         "type": "boolean"
      },
      "supportAvailability": {
         "type": "string"
      },
      "supportResponseTime": {
         "type": "string"
      },
      "incidentEscalation": {
         "type": "boolean"
      },
      "supportTypes": {
         "type": "array",
         "uniqueItems": true,
         "maxItems": 5,
         "items": {
            "type": "string",
            "pattern": "^(Service desk|Email|Phone|Live chat|Onsite)$"
         }
      },
      "vendorCertifications": {
         "type": "array",
         "maxItems": 10,
         "items": {
            "type": "string"
         }
      }
   },
   "required": [
      "id",
      "supplierId",
      "lot",
      "title",
      "lastUpdated",
      "lastUpdatedByEmail",
      "lastCompleted",
      "lastCompletedByEmail",
      "serviceTypes",
      "serviceName",
      "serviceSummary",
      "serviceBenefits",
      "serviceFeatures",
      "serviceDefinitionDocument",
      "serviceDefinitionDocumentURL",
      "termsAndConditionsDocument",
      "termsAndConditionsDocumentURL",
      "minimumContractPeriod",
      "terminationCost",
      "priceMin",
      "priceUnit",
      "priceString",
      "vatIncluded",
      "educationPricing",
      "pricingDocument",
      "pricingDocumentURL",
      "supportForThirdParties",
      "supportAvailability",
      "supportResponseTime",
      "incidentEscalation",
      "supportTypes"
   ]
}

=== Crown-Commercial-Service/digitalmarketplace-api/example_listings/G6-SCS.json
{
   "id": "1234567890123459",
   "supplierId": 1,
   "lot": "SCS",
   "title": "Finally, an SCS \"Service\u0027: ]",
   "lastUpdated": "2014-12-23T14:53:17Z",
   "lastUpdatedByEmail": "supplier@digital.cabinet-office.gov.uk",
   "lastCompleted": "2014-12-23T14:53:20Z",
   "lastCompletedByEmail": "supplier@digital.cabinet-office.gov.uk",
   "serviceTypes": [
      "Implementation",
      "Ongoing support",
      "Planning"
   ],
   "serviceName": "Finally, an SCS \"Service\u0027: ]",
   "serviceSummary": "\" I have a summary\r\n\r\n]",
   "serviceBenefits": [
      "Big jobs!"
   ],
   "serviceFeatures": [
      "[Blah \"Blah\" Kev\u0027s test"
   ],
   "serviceDefinitionDocument": "Poster_MJ_s_Charity_Concert_WLC.pdf",
   "serviceDefinitionDocumentURL": "https://s3-eu-west-1.amazonaws.com/gds-g6-submission-bucket-local/1/15/15-service-definition-document.pdf",
   "termsAndConditionsDocument": "Poster_MJ_s_Charity_Concert_WLC.pdf",
   "minimumContractPeriod": "Hour",
   "terminationCost": true,
   "termsAndConditionsDocumentURL": "https://s3-eu-west-1.amazonaws.com/gds-g6-submission-bucket-local/1/15/15-terms-and-condtions.pdf",
   "priceInterval": "6 months",
   "priceUnit": "Licence",
   "educationPricing": false,
   "vatIncluded": true,
   "priceString": "Â£34.65 per licence per 6 months",
   "sfiaRateDocument": "Poster_MJ_s_Charity_Concert_WLC.pdf",
   "pricingDocument": "Poster_MJ_s_Charity_Concert_WLC.pdf",
   "priceMin": 34.65,
   "sfiaRateDocumentURL": "https://s3-eu-west-1.amazonaws.com/gds-g6-submission-bucket-local/1/15/15-sfia-rate-card.pdf",
   "pricingDocumentURL": "https://s3-eu-west-1.amazonaws.com/gds-g6-submission-bucket-local/1/15/15-pricing-document.pdf",
   "supportForThirdParties": true,
   "supportAvailability": "sjhdgf jhsdgf jhsg fhj gh 6\u0026*%\u0026 \u0026*",
   "supportResponseTime": "sfsdf ",
   "incidentEscalation": false,
   "supportTypes": [
      "Service desk",
      "Live chat",
      "Onsite"
   ],
   "vendorCertifications": [
      "Kev\u0027s test \"Blah\" ] : \u0027",
      "A-Level maths"
   ]
}
