=== Crown-Commercial-Service/digitalmarketplace-api/json_schemas/suppliers.json
{
  "$schema": "http://json-schema.org/schema#",
  "additionalProperties": false,
  "properties": {
    "clients": {
      "items": {
        "type": "string"
      },
      "maxItems": 10,
      "minItems": 0,
      "type": "array"
    },
    "companiesHouseNumber": {
      "oneOf": [
        {
          "maxLength": 8,
          "minLength": 8,
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "contactInformation": {
      "items": {
        "$ref": "file:json_schemas/contact-information.json"
      },
      "minItems": 1,
      "type": "array"
    },
    "description": {
      "type": "string"
    },
    "dunsNumber": {
      "pattern": "^[0-9]+$",
      "type": "string"
    },
    "eSourcingId": {
      "pattern": "^[0-9]+$",
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "organisationSize": {
      "type": "string"
    },
    "otherCompanyRegistrationNumber": {
      "type": "string"
    },
    "registeredName": {
      "type": "string"
    },
    "registrationCountry": {
      "type": "string"
    },
    "registrationDate": {
      "type": "string"
    },
    "tradingStatus": {
      "type": "string"
    },
    "vatNumber": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "name"
  ],
  "title": "Schema to validate updates to supplier data",
  "type": "object"
}

=== Crown-Commercial-Service/digitalmarketplace-api/example_listings/Supplier.json
{
  "id": 123456,
  "name": "Example Company Limited",
  "description": "Example Company Limited is an innovation station sensation; we deliver software so bleeding edge you literally won't be able to run any of it on your systems.",
  "contactInformation": [
    {
      "website": "www.examplecompany.biz",
      "contactName": "John Example",
      "email": "j@examplecompany.biz",
      "phoneNumber": "07309404738",
      "address1": "123 Fake Street",
      "city": "London",
      "country": "United Kingdom",
      "postcode": "F4 K1E"
    },
    {
      "id": 1,
      "website": "http://www.don.com?fref=ts",
      "contactName": "Don",
      "email": "don@don.com",
      "phoneNumber": "020 7918 9200",
      "address1": "4 Don Hill",
      "address2": "Flat 1",
      "city": "London",
      "country": "UK",
      "postcode": "EC1A D0N"
    }
  ],
  "dunsNumber": "333333333",
  "eSourcingId": "333333",
  "clients":
  [
    "UK Ministry of Defence",
    "Astula Ltd",
    "Bedrock Communications Ltd"
  ]
}
